### ISSUE TITLE
Compilation error with g++ 4.8 / clang 3.4

### ISSUE THREAD

**Issue by speth** [pfultz2/ClangComplete#1]
I get the following error when trying to compile using g++ 4.8:

```
complete.cpp: In function ‘std::shared_ptr<async_translation_unit> get_tu(const char*, const char**, int, int)’:
complete.cpp:536:39: error: could not convert ‘lock.std::unique_lock<_Mutex>::lock<std::timed_mutex>()’ from ‘void’ to ‘std::shared_ptr<async_translation_unit>’
     if (timeout < 0) return lock.lock();
                                       ^
make: *** [all] Error 1
```

on commit 40e4bbb . This error does not occur with commit 8606a74.
